indomit/progress_knight_2

- js/classes.js
- js/main.js
Improve the code quality of the codebase.
**Goals:**
- Use less global variables (`const x = 1` instead of `x = 1`) because the variable can be used anywhere and may cause horrible bugs. These are some variables which were globally accessable:
- Make more variables immutable to prevent bugs.
- Remove some redundant code (ex: using a variable only once)
- Make the codebase smaller. Less is almost always better.
These changes should not affect the gameplay in any way. If I have made a mistake feel free to point it out!
> Improve the code quality

- index.html
- js/main.js
- js/ui.js
- js/utils.js
* Move the ui code into `ui.js`
No gameplay should be affected. The main file has gotten ~2x smaller when this PR is merged. This will allow me to further focus on rewriting/removing dumb code to make adding new features easier!
> Move UI functions a seperate file

- index.html
- js/main.js
- js/utils.js
* Moved a few helper functions to a file called `utils.js`
* Renamed a few functions to make the use more clear
* Removed some dead code
* Minor code formatting
No gameplay should be affected.
> Even more code formatting

- index.html
- js/main.js
- js/ui.js
- js/utils.js
* Fix a few small bugs (number formatting and currency displaying)
* Added a visual message when an error gets thrown. This way users know when it's a bug or a feature and can report it better.
* Make the first timewarping skill slightly stronger because 80% of the early game is just spent watching till you can rebirth
> Fix a few small visual bugs, add better error detection and make the first timewarping skill slightly stronger

- js/main.js
I fixed some incorrect spelling and grammar in some of the tooltips, including those in jobs, skills, and other tooltips.
> Fix spelling and grammar in various tooltips

- index.html
- js/main.js
There were some more errors in spelling and grammar in other game texts, so I went ahead and fixed them.
> Fix some more spelling and grammar in other texts

- index.html
- js/challenges.js
- js/main.js
- js/ui.js
* Create a 5th challenge
* Make the other challenges a bit stronger
> Improve challenges and add a 5th one

- js/classes.js
- js/main.js
- js/ui.js
I've made many minor fixes to comments, wording, and other code throughout this project.
Some of these fixes may affect gameplay, including but not limited to the following:
* Bankruptcy now triggers only when both bank balance and its derivative are negative.
* The following things now only happen while the game is running (not paused or stopped due to age):
- `gameData.realTimeRun` incrementing
- Passive evil gain
> Many minor gameplay, wording, and code fixes

- js/main.js
When i have the game in a hidden tab, it continue to use CPU to update the UI, with this change, it is only updated when the game is back on screen.
> avoid updating ui when window is hidden.

- index.html
The changed lines refer to multipliers, so use the word "multiplies" where appropriate.
> Clarify "increases" to "multiplies"

- index.html
The "A miracle" dark matter upgrade keeps "Magic Eye" on Dark Matter *and lower* resets, not just on Dark Matter resets.
> Fix "A Miracle" description to what it actually does

- js/ui.js
There were two functions with exactly the same code, one of which named "updateRequiredRows" and the other named "renderRequirementsForCategoryType". The latter function was only called one unique time while the former is called from multiple different places.
Consolidate the two functions into one to improve maintainability for that part of the code.
> Deduplicate the "updateRequiredRows" function

- js/challenges.js
- js/classes.js
- js/dark_matter.js
- js/main.js
- js/ui.js
- js/utils.js
Remove all trailing spaces from each line of the code in all `*.js` files except the two library files (`HackTimer.js` and `math.js`).
This saves a few bytes on the code size and is another step towards cleaning up the codebase.
> Trim trailing spaces from the code

- js/main.js
Remove the old `peekThemeFromSave` function from the code as it has been superseded by `peekSettingFromSave`.
> Remove old `peekThemeFromSave` function

- js/main.js
> Fix Supercluster and Galaxy Filament effect

- changelog.txt
- css/styles.css
- index.html
- js/classes.js
- js/data.js
- js/main.js
- js/ui.js
Summary:
* Improves performance by caching
* Fixes a few bugs
* Adds an option to disable dangerous keybinds
* Improve the code quality
> Improve performance, fix a few bugs and improve the code qualitity.

- js/classes.js
- js/main.js
- js/utils.js
Reverts indomit/progress_knight_2#70
didn't work correctly with pause button
> Revert "Replace BigInts with Logarithms"

- js/dark_matter.js
- js/ui.js
4c5024627e02a128eec75361ba368ca72d5d97b4 missed some renames of Dark Matter Skills to Dark Matter Abilities, including one in their respec button's confirmation text.
> Finish renaming Dark Matter Skills to Abilities

- index.html
- js/tooltips.js
This pull request simply changes the word "existance" to "existence" in the game's text.
https://www.thefreedictionary.com/existance
> localization: Correct misspellings of existance->existence

- css/w3.css
- index.html
In this pull request I simply replaced the external w3.css with an internal copy. The site performed slightly better, especially on desktop.
> Small performance optimization
