indomit/progress_knight_2

js/main.js
Before this change, importing an empty save would give the same error as importing a corrupt save.
This has been changed; importing an empty save now gives a different error message saying that the imported save data is empty.
=> Add a better error message when importing an empty save

js/main.js
Previously, the fifth challenge would not reset on game completion, causing Evil gain for subsequent runs to be substantially greater.
=> Fix fifth challenge not resetting on game completion

index.html
Fixes a regression caused by one of my changes in 1a9dcfcb970a0e8b0319cc6c0653f8de294118ba (#7).
The regression was that when the remaining experience amounts were small enough, the "Xp left" text would have a line break between "Xp" and "left", making that text take up 2 lines and causing the headers to be somewhat taller and take up more space.
Replacing the regular space with a non-breaking space solves this by effectively telling the renderer to treat the whole string "Xp&nbsp;left" as one word.
=> Use NBSP on "Xp left" to fix a regression in #7

js/ui.js, js/utils.js
The lifespan display now uses the same precision as the age display to allow better comparisons when getting close to end of lifespan. Previously, the lifespan display used a flat 0 digits after the decimal, causing all values for the lifespan (in years) from 1000-1999 to display as "1k", 2000-2999 as "2k", and so on, and the same for millions (1000000 to 1999999 -> "1M").
Furthermore, all places which display a precise time now use days for durations longer than 24 hours and years for durations longer than 365 days (not that anyone would play this long).
This is most helpful during early-game, full-life runs, and while running challenges.
=> Increase lifespan precision and better format long time durations

css/currencies.css, index.html, js/main.js, js/ui.js, js/utils.js
Multiple new currency options are added, along with a setting to go with them.
* Medieval: The original coin currencies in Progress Knight and the default set for this mod.
* Extended: Adds many new coin currencies with increasing values. The currencies are from a set originally curated by @veprogames for their mod.
* British: The old £sd system used in England until the mid-20th century.
* Modern: Currency used in the modern world, with an old silver coin now worth one dollar.
Note: I was unable to render the following characters in the "Extended" currency set on my system; they have been replaced. Feel free to suggest better alternatives if you want.
* 𐅍 U+1014D "GREEK ACROPHONIC ATTIC ONE THOUSAND TALENTS" with value 1e20 has been replaced with Ξ.
* 𐙋 U+1064B "LINEAR A SIGN AB122" with …
=> More coin currencies and new currency notations

index.html, js/main.js
The new "Dark Matter Skills" upgrades had generic "Increases" and "Decreases" effects, but the actual effect is that it multiplies or divides a certain value (such as evil or essence gain). I've fixed the descriptions to reflect this.
There was some incorrect punctuation in some of the new strings added in the same update; the punctuation is now fixed.
=> Fix some grammar in new Dark Matter content

index.html, js/main.js, js/ui.js
Added text displaying the total amount of game time elapsed since first start or hard reset.
Like the real time played indicator, the total game time counter does not reset on any form of prestige.
=> Add total game time elapsed

index.html, js/challenges.js, js/main.js, js/ui.js
Each challenge now displays its goal, which is the minimum required amount of the challenge stat (happiness, income, and game speed respectively for the first 3 challenges) that will allow completing the challenge to increase the reward.
Furthermore, a display error in Time Warping has been fixed (reproducible while running the 3rd challenge).
=> Challenges now have visible goals

changelog.txt
"too" in "too large" was misspelled as "to"; that is now fixed.
=> Fix a minor typo in the 2.2.4 changelog

js/ui.js, js/utils.js
All task levels greater than or equal to 100,000 are now formatted (abbreviated), wherever they may appear, and levels below 100,000 have commas in them.
Note: The "adding commas to level numbers" is implemented using JavaScript's `toLocaleString` method, which may behave differently depending on the client's region.
=> Format large task levels

index.html, js/dark_matter.js, js/ui.js
Limit the total number of purchased Dark Orb Generators to prevent unnecessarily spending valuable Dark Matter on something that's of no use past a certain point.
The limit triggers when the daily generation of Dark Matter goes infinite; therefore, the exact limit may vary depending on whether a certain Essence milestone is active.
=> Limit Dark Orb Generators

js/main.js
The "corrupted save" error message was missing a comma in two occurrences; that is now fixed, making the punctuation consistent with other occurrences of the same message.
=> Add missing commas to corrupted save error messages

js/main.js
Once Dark Orbs (or any other number) went infinite, the next time the game was paused for any reason, that number would be set to NaN, as the current game speed of 0, times the daily production of Infinity, equals NaN, which, when added to any other number, equals NaN.
This is now fixed: if Dark Orbs per day is infinite, then Dark Orbs is also always infinite.
Furthermore, this bug may have already been triggered at least once by somebody, causing their save's Dark Orbs value to be NaN. A check has been added that will set Dark Orbs to 0 on load if that's the case.
=> Fix the possibility of Dark Orbs being set to NaN

index.html, js/classes.js, js/main.js, js/tooltips.js
The universe is at least a trillion, trillion times bigger than a planet, which means there's definitely room for several new properties.
All of the new properties are unlocked after going Heroic, with the last one requiring a googol dollars to unlock or the equivalent in other currencies. This is to give players something to do with their 5e5 Dark Matter and an incentive to max out everything available, as the last property can be unlocked in under 10 minutes from the start of a rebirth if done right.
Each property has just 20% more happiness (additive) than the last after the previous endgame property; this is to avoid breaking other future plans, but the effects can be strengthened if needed (my original intention was for the properties to gradually ramp up to around 1e60 Happiness at …
=> Add 5 new shop items between Planet and The Universe

js/main.js, js/ui.js
The font size was loaded from the save data during UI initialization, but the other settings weren't, causing things like layout and currency notation to visually reset whenever a player (re)loaded the game.
This is now fixed by replacing the `peekFontSizeFromSave` function with its more general counterpart, `peekSettingFromSave`, and using that new function where appropriate.
=> Fix: most settings were not loaded from save on game load

index.html, js/main.js, js/ui.js
Adds a description for what will happen when collapsing the universe, and fix some grammar in earlier parts of amulet lore.
Preview when first reaching Dark Matter reset requirement:
=> Add reset description for collapsing the universe

js/classes.js, js/main.js, js/ui.js, js/utils.js
The current game loading code sucks. The order is extremely important.  The definition of jobs, skills, shop and milestones are at the top while the requirements are at the bottom. The ultimate goal is seperate all this into another file so our `main.js` file gets smaller. Converting the `document.getElementById` calls to query selectors allows us to define the requirements and get the actual elements at a later time. 
It would be really awesome if some else can look at this PR and also test it :D This change is quite big so I might have missed something.
=> Convert the element system of the requirements to query selectors

js/dark_matter.js
The text in the confirmation prompt for resetting Dark Matter Skills now refers to them specifically instead of using a more general term.
=> Clarify the "reset Dark Matter Skills" prompt

index.html, js/ui.js
There was an unused variable in the game data called "realtimeRun" which was incremented endlessly and (after the Dark Matter update) never reset, effectively making it a counter for the total online time played since the start of the game.
Display the variable in the stats as such and shift the "X days ago" to the end of the "date of game start" line.
This allows players to see effectively the true total amount of real time spent in the game, potentially allowing for some sort of full-game "speedrun".
=> Show the total amount of online time played on a save

index.html, js/challenges.js, js/main.js, js/ui.js
Properly keep track of each prestige layer's reset time separately and make sure that e.g. embracing evil does not reset time since last transcension.
Entering/exiting challenges effectively does an evil reset, so reset the timers as if an evil reset was performed.
The evil/s and essence/s displays now use the respective reset times instead of `gameData.realtime`.
This is cosmetic only for now, but one way this could be useful is if Faint Hope was not reset whenever the player embraced evil (e.g. whilst pushing challenges).
=> Keep track of reset time separately per prestige layer

index.html, js/challenges.js, js/ui.js, js/utils.js
This allows Great Chairman to count towards challenge 5 ("Legends never die") progress much more quickly compared to regular Chairman, to better reward players who reach heroics in that challenge.
For example, if a player reached Great Chairman level 1,000, that would count the same as reaching 1 million regular Chairman levels in terms of challenge progress, similar to how 1,000 Great Concentration is equivalent to about 1 million regular Concentration in its effect.
The result is that with the right setup, an Evil gain multiplier of over 15kx from the challenge can be achieved, compared to just 500x before this change.
The added code is designed such that if any additional challenges have task level based goals, they can easily receive a boost in progress from the job/skill becoming …
=> Recognize Great Chairman in "Legends never die" challenge progress

css/styles.css
A recent change resulted in tooltips taking 25% of the width of the display, regardless of font size, causing overflow to the right at smaller font sizes. This has been changed; the tooltips now fit within the column and their width is dependent on the font size, which helps to avoid overflow.
=> Fix the width of tooltips

js/main.js, js/ui.js
The function named `isNextDarkMatterSkillInReach` returns whether the next dark **magic** skill is in reach, not whether the next dark matter skill is in reach. Change its name to match.
=> Use correct name for new function

js/main.js
The "Heroic milestones" and "Dark milestones" categories used to be visible as soon as milestones were unlocked, despite them being far off at that point in progression. Hide these categories until the last milestone in the previous category is unlocked.
=> Add requirements for milestone categories

changelog.txt
Previous changelog entries used asterisks to denote list items, but the new entry used hyphens. Both are acceptable in Markdown, but this change makes it consistent in plaintext.
=> Fix bullet point markers in the 2.2.9 changelog

js/main.js, js/tooltips.js
This renames the shop item originally titled "Stairway to hell" so it is now called "Highway to hell."
=> Rename a shop item: "Stairway to hell" → "Highway to hell"

js/main.js, js/ui.js, js/utils.js
Converts tabs to spaces on all `*.js` files except the two library files (`HackTimer.js` and `math.js`).
The affected files mainly use spaces for indentation instead of tabs, so this makes it more consistent.
=> Convert tabs to spaces on most code files

js/dark_matter.js
If Life Coach were to retain its original formula, then if the Dark Orb cap was somehow raised (or Dark Orb upgrade costs reduced), that would make the upgrade very OP beyond late game.
By changing the formula beyond level 30, the effect of Life Coach at level 60 (cost 1e600 Dark Orbs) is reduced from x1e60 to x1e39, which results in more manageable bank balance.
Note: as the maximum level of Life Coach that can be bought for less than 1.80e308 Dark Orbs is 30, this won't actually take effect until the Dark Orb cap is raised.
=> Weaken Life Coach effect formula beyond level 30

js/main.js
Faint Hope is a milestone unlocked with Essence, it multiplies Essence gain over time, and Essence is gained by transcending, so it makes sense for Faint Hope to not reset until transcension.
This allows a player to push challenges and build up Faint Hope multiplier at the same time.
For example, a player could transcend, spend an hour in each of the 5 challenges, spend by an hour outside of challenges, and get a similar buff from Faint Hope as a player that spent 6 consecutive hours outside of challenges since last transcension.
=> Don't reset Faint Hope time until transcension

js/ui.js
There are two identical parts of the code in two different functions, responsible for piecing together the correct tooltip for jobs and skills yet to become Heroic while that mechanic is unlocked.
This PR deduplicates and moves the code to its own function, which improves maintainability by not having to apply changes to the code in multiple different places.
Save file for testing (right at start of first Heroic unlocks): [savefile.txt](https://github.com/indomit/progress_knight_2/files/10723423/savefile.txt)
=> Deduplicate code for heroic required tooltips

js/main.js
The item multiplies Evil **gain**, not (effective) Evil.
=> Fix f3fbf07bd: Clarify effect of "Highway to hell"

js/main.js
The function was never called anywhere and is therefore unused; hence its removal.
=> Remove unused function `resettask`

index.html
The description of the challenge "The darkest time" when taken literally would currently imply all challenges, current and future, would be active at once. This is not the case; only the previous challenges (1-5) are active at once when in this challenge.
=> Clarify the challenge 6 description a little bit

index.html, js/ui.js
After Metaverse, lifespan is infinite except when in challenges 5 or 6 (which ordinally reduces lifespan); however that is not accounted for in the description.
Add text to the challenge 5 description stating the lifespan buff from Metaverse is disabled when in that challenge. This text only shows after the first Metaverse reset.
Note to maintainers: don't merge this if you will merge #78 instead as that PR makes this PR redundant.
=> Clarify the lifespan debuff in the challenge 5 description post-Metaverse

js/main.js
The function previously calculated the expression `1.0 / updateSpeed` many times; the value is now calculated once per frame and stored in a constant; said constant is then used instead.
=> Optimize `increaseRealtime` a bit

js/main.js, js/metaverse.js, js/ui.js
Previously, pausing the game would zero out hypercube production displays and make hypercube time estimates become infinite, which may not be wanted by some players.
Now, hypercube production and time estimates remain at a sane value and pause while the game is paused.
=> Fix hypercube production displays while game is paused

js/metaverse.js
Currently, when you would unlock Metaverse Perks on your next Metaverse, the Hypercube Cap is displayed as a finite value less than e308, which is incorrect as the true cap jumps to that value on the metaverse reset that unlocks metaverse perks.
=> Show next hypercube cap as Infinity on perk unlock

js/ui.js
My last commit touching this code mistakenly removed a factor of updateSpeed (20) from the displayed hypercube production. This is now fixed; the factor is in which should make the displayed value match actual production.
The underlying cause was my brief misunderstanding of what two functions did:
- Suppose a production rate of 5 hypercubes per day and a game speed of 40 days per second.
- The goal is to have the 'hypercubes per second' display say '200 / s'.
- The code previously there would call `applyUnpausedSpeed()` on the result of `getHypercubeGeneration()` (5 in this case). `applyUnpausedSpeed()` would take this 5, multiply it by `getUnpausedGameSpeed()` (40), then divide it by `updateSpeed` (20) to get 10, which is the hypercubes generated per **tick**, not per second.
- The …
=> Fix the hypercube per-second display again

js/classes.js, js/main.js, js/utils.js
This gives a decent speedup post e305 xp, and increases the iterations in `increaseXp`.
This does cause a small slowdown (~10%) in level gains past e305 xp, due to the removal of some aggresive rounding in the players favor while converting to BigInt.
This also fixes an issue that the BigInt xp is not reset on rebirth, which I couldn't notify you of elsewhere because the project doesn't have an Issues tab, and I'm not making a pull request for a single line of code
=> Replace BigInts with Logarithms

index.html
With the changes in 4c5024627e02a128eec75361ba368ca72d5d97b4, the C5 text post-Metaverse had an inconsistency, where the "Lifespan is now Infinity" part didn't match the "Lifespan is now infinite" the first line in the text of the Metaverse tab was changed to.
Change "Lifespan is now Infinity" to "infinite lifespan" in the C5 text post-Metaverse to resolve the inconsistency.
If needed, the C5 text post-Metaverse can instead be changed to mention "Lifespan is now infinite" to preserve a literal match.
=> Fix an inconsistency in the C5 text post-Metaverse

js/main.js, js/ui.js
The rebirth functions don't check to see if you meet the requirements for the respective rebirth before executing, this adds those checks.
If you are writing automation scripts for the game, without the check you can do early rebirths by firing the functions as exist now.  The script author needs to check to see if conditions are met otherwise can "cheat" the run with early rebirths.
=> Add a validition check before each of the rebirth functions
